### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by skrawcz** [hugobowne/AI-for-SWEs#4]
Given our example app that we're building, I was thinking that these are things we want to check off:

concepts to explain via first principles and thread into examples:
- [ ]  - API call + knobs 
- [ ]  - prompt engineering
- [ ]  - completion vs chat 
- [ ]  - non-determinism -> they're generative models
- [ ]  - pipeline (rigid structure) versus agent (making decisions as to what to do next)
- [ ]  - evaluating an output (some basic overview)
- [ ]  - what is an embedding (some basic overview) 
- [ ]  - what is a vector store (some basic overview)
- [ ]  - prompt context creation (what RAG is)
- [ ]  - structured outputs & function calling (why, when)
- [ ]  - observability needs over all of this (micro vs macro)
- [ ]  - SDLC to fit this all in (agile doesn't work, need to account for iteration needs + observability + getting into the data)
- [ ]  - frameworks: know what you’re buying into

**Comment by skrawcz** [comment]
@hugobowne ^ thoughts?

**Comment by hugobowne** [comment]
yeah these are all great and along the lines of what i was thinking. there are a few other things, such as prompt templates.

also interested in your thoughts on "non-determinism" -- this isn't so much because they're generative models, but because they're data-powered (in some sense)?

**Comment by hugobowne** [comment]
also it's a good question how much to say about embeddings and vector stores in a 3 hours workshop

there's an argument that we should actually spend a not insignificant amount of time on embeddings tbh

**Comment by skrawcz** [comment]
> also interested in your thoughts on "non-determinism" -- this isn't so much because they're generative models, but because they're data-powered (in some sense)?

same inputs -> different outputs.

then small perturbations of inputs that look similar make this worse.

**Comment by hugobowne** [comment]
yes im happy to but it would help to see the code/apps you've proposed [here](https://github.com/hugobowne/AI-for-SWEs/issues/5) as that will impact how and when we introduce new concepts
